# Generated by Django 5.0.2 on 2024-02-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300)),
                ('status', models.CharField(blank=True, choices=[('DEFINED', 'Defined'), ('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DEFINED', max_length=20)),
                ('assignee', models.CharField(max_length=20)),
                ('ETA', models.DateField()),
                ('risk_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
