# Generated by Django 5.0.2 on 2024-02-12 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300)),
                ('status', models.CharField(blank=True, choices=[('TO_DO', 'To Do'), ('DEFINED', 'Defined'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='TO_DO', max_length=20)),
                ('assignee', models.CharField(max_length=300)),
                ('ETA', models.DateField()),
                ('risk_flag', models.BooleanField(default=False)),
                ('manage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
